package br.com.miriageekstore.catalog.application.usecase;

import br.com.miriageekstore.catalog.domain.exception.ProductNotFoundException;
import br.com.miriageekstore.catalog.domain.exception.ProductSkuAlreadyExistsException;
import br.com.miriageekstore.catalog.domain.model.CategoryId;
import br.com.miriageekstore.catalog.domain.model.Product;
import br.com.miriageekstore.catalog.domain.model.ProductVariant;
import br.com.miriageekstore.catalog.domain.model.Sku;
import br.com.miriageekstore.catalog.domain.port.in.AddVariantCommand;
import br.com.miriageekstore.catalog.domain.port.out.ProductRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class AddVariantUseCaseTest {

    @Mock ProductRepository productRepository;
    @InjectMocks AddVariantUseCaseImpl useCase;

    @Test
    void shouldAddVariantWithCustomSku() {
        var product = product();
        when(productRepository.findById(any())).thenReturn(Optional.of(product));
        when(productRepository.existsBySku("NOVO-SKU")).thenReturn(false);
        when(productRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

        var result = useCase.execute(command(product.getId().value(), "NOVO-SKU"));

        assertThat(result.sku()).isEqualTo("NOVO-SKU");
        assertThat(result.active()).isTrue();
        verify(productRepository).save(any());
    }

    @Test
    void shouldAddVariantWithAutoGeneratedSku() {
        var product = product();
        when(productRepository.findById(any())).thenReturn(Optional.of(product));
        when(productRepository.existsBySku(anyString())).thenReturn(false);
        when(productRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

        var result = useCase.execute(command(product.getId().value(), null));

        assertThat(result.sku()).isNotBlank();
        assertThat(result.active()).isTrue();
    }

    @Test
    void shouldThrowWhenProductNotFound() {
        when(productRepository.findById(any())).thenReturn(Optional.empty());

        assertThatThrownBy(() -> useCase.execute(command(UUID.randomUUID(), "SKU-X")))
                .isInstanceOf(ProductNotFoundException.class);

        verify(productRepository, never()).save(any());
    }

    @Test
    void shouldThrowWhenSkuAlreadyExists() {
        var product = product();
        when(productRepository.findById(any())).thenReturn(Optional.of(product));
        when(productRepository.existsBySku("DUPLICADO")).thenReturn(true);

        assertThatThrownBy(() -> useCase.execute(command(product.getId().value(), "DUPLICADO")))
                .isInstanceOf(ProductSkuAlreadyExistsException.class);

        verify(productRepository, never()).save(any());
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private Product product() {
        var v = ProductVariant.create("Cor", "Preto", BigDecimal.valueOf(99), 5, new Sku("SKU-001"),
                BigDecimal.valueOf(0.350), BigDecimal.valueOf(15), BigDecimal.valueOf(10), BigDecimal.valueOf(20));
        return Product.create("Funko Batman", "Desc", CategoryId.of(UUID.randomUUID()), false, List.of(v));
    }

    private AddVariantCommand command(UUID productId, String sku) {
        return new AddVariantCommand(productId, "Tamanho", "M", BigDecimal.valueOf(59.90), 3, sku,
                BigDecimal.valueOf(0.350), BigDecimal.valueOf(15), BigDecimal.valueOf(10), BigDecimal.valueOf(20));
    }
}
